name: cleanup
on: 
  workflow_run:
    workflows: [deploy_script_linode]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: run cleanup script
        run: |
          chmod +x ./scripts/cleanup.sh
          ./scripts/cleanup.sh jcotoBan postgresql-occ
        env:
          gh_token: ${{ secrets.ACTIONS_SECRET }}
          TOKEN_PASSWORD: ${{ secrets.LINODE_API_TOKEN }}